Optimized the conditions
Signed-off-by: YashTatkondawar <yashtatkondawar@gmail.com>

diff --git a/requirements b/requirements
--- a/requirements
+++ b/requirements
@@ -15,43 +15,32 @@ if [[ ${OS_NAME} == *"Red Hat"* || ${OS_NAME} == *"CentOS"* ]]; then PKG_MANAGER
 echo
 
 install_nodejs () {
-  isNodeInstalled=`which node` || echo ''
-    if [ "$isNodeInstalled" != "" ]; then
-      # Check if nodejs version is < 14.x
-      currentNodeVer=`node -v`
-      requiredNodeVer="v14.15.5"
-      if [ "$(printf '%s\n' "$requiredNodeVer" "$currentNodeVer" | sort -V | head -n1)" = "$requiredNodeVer" ]; then
-        echo "nodejs version: ${currentNodeVer}"
-        echo "npm version: `npm -v`"
-      else
-        curl -L https://deb.nodesource.com/setup_14.x | sudo -E bash -
-        sudo $1 install -y nodejs
-      fi
-    else
+  isNodeInstalled=`which node` && currentNodeVer=`node -v` || echo ''
+  requiredNodeVer="v14.15.5"
+  # Check if nodejs is installed or if installed version is < 14.x
+  if [[ "$isNodeInstalled" = "" ]] || [[ "$(printf '%s\n' "$requiredNodeVer" "$currentNodeVer" | sort -V | head -n1)" != "$requiredNodeVer" ]]; then
       curl -L https://deb.nodesource.com/setup_14.x | sudo -E bash -
       sudo $1 install -y nodejs
-    fi
+  else
+    echo "nodejs version: ${currentNodeVer}"
+    echo "npm version: `npm -v`"
+  fi
 }
 
 
 
-# Don't run yarn build as root; if you had done, reclaim ownership for ~/.npm and ~/.config
-# sudo chown -R $USER:$GROUP ~/.npm
-# sudo chown -R $USER:$GROUP ~/.config
+# Don't run yarn build as root; if you had done, reclaim ownership for .npm and .config files
+# sudo chown -R $USER:$GROUP $(sudo find / -type d -name .npm 2>/dev/null)
+# sudo chown -R $USER:$GROUP $(sudo find / -type d -name .config 2>/dev/null)
 
 install_yarn () {
-    isYarnInstalled=`which yarn`|| echo ''
-    if [ "$isYarnInstalled" != "" ]; then
-      # Check if yarn version is < 1.21.x
-      currentYarnVer=`yarn -v`
-      requiredYarnVer="1.21.0"
-      if [ "$(printf '%s\n' "$requiredYarnVer" "$currentYarnVer" | sort -V | head -n1)" = "$requiredYarnVer" ]; then
-        echo "yarn version: ${currentYarnVer}"
-      else
+    isYarnInstalled=`which yarn` && currentYarnVer=`yarn -v` || echo ''
+    requiredYarnVer="1.21.0"
+    # Check if yarn is installed or if installed version is < 1.21.x
+    if [[ "$isYarnInstalled" = "" ]] || [[ "$(printf '%s\n' "$requiredYarnVer" "$currentYarnVer" | sort -V | head -n1)" != "$requiredYarnVer" ]]; then
         sudo npm install -g yarn
-      fi
     else
-      sudo npm install -g yarn
+      echo "yarn version: ${currentYarnVer}"
     fi
 }
 
